name: Build macOS App

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: macos-latest  # 使用 GitHub 的 macOS 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: 创建虚拟环境
      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv  # 创建虚拟环境
          source venv/bin/activate  # 激活虚拟环境

      # Step 2: 升级 setuptools 和 pip，并使用 PEP 517 安装依赖
      - name: Upgrade setuptools and install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install --use-pep517 -r requirements.txt
          pip install --use-pep517 py2app  # 安装 py2app 并使用 PEP 517

      # Step 3: 构建 .app 文件（确保 iconfile 路径正确，或删除 iconfile 选项）
      - name: Build macOS App using py2app
        run: |
          source venv/bin/activate
          python setup.py py2app

      # Step 4: 上传打包结果
      - name: Archive build result
        uses: actions/upload-artifact@v3
        with:
          name: mac-app  # 打包的文件名
          path: dist/    # 上传 dist 文件夹下的内容
