name: Build macOS App

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 检查代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 创建并激活虚拟环境
      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv  # 创建虚拟环境
          source venv/bin/activate  # 激活虚拟环境

      # 确认虚拟环境已激活并升级 pip
      - name: Upgrade pip in virtual environment
        run: |
          source venv/bin/activate
          python3 -m pip install --upgrade pip  # 升级 pip
          pip --version  # 输出 pip 版本信息

      # 安装依赖项（在虚拟环境中）
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install py2app

      # 使用 py2app 打包应用程序（在虚拟环境中）
      - name: Build macOS App using py2app
        run: |
          source venv/bin/activate
          python setup.py py2app

      # 上传打包结果
      - name: Archive build result
        uses: actions/upload-artifact@v3
        with:
          name: mac-app
          path: dist/
